### ISSUE TITLE
replicação nos repositórios maven

### ISSUE THREAD

**Issue by jacksonemmerich** [jhemarcos/cns#4]
Caro Jean, a versão do cns1.0.0 ainda está com aquele  erro do endpoint de produção estar com o hm no nome, que remete ao link de homologação, 
` private static final String CADSUS_ENDPOINT_PRODUCAO = "https://servicos**hm**.saude.gov.br/cadsus/PDQSupplier";`, 
precisamos que submeta aos repositórios do maven uma versão com a correção, 
`private static final String CADSUS_ENDPOINT_PRODUCAO = "https://servicos.saude.gov.br/cadsus/PDQSupplier";` , para que possamos baixar no pom.xml a versão cns-1.0.1 com a correção. Grato!

**Comment by jhemarcos** [comment]
Olá @jacksonemmerich! Irei realizar a publicação da versão atualizada nesta semana. Conforme mencionei, como este projeto não será mantido por mim, sugiro que já iniciem os procedimentos para que vocês mesmos publiquem suas versões no Maven Central/Nexus Repository. Caso precisem urgentemente da versão atualizada, vocês podem gerar um _.jar_ dessa lib e importar o arquivo diretamente no projeto.
Abraços!

**Comment by jacksonemmerich** [comment]
@jhemarcos já tentei de tudo e não consigo criar o jar da api, o erro que dá é justamente da biblioteca que ele baixa dos repositórios maven, tentei copiar o projeto e tentei enviar para o repositório maven, mas tbm não consegui pois dava diversos erros, e problemas com a biblioteca do maven, bem até agora não consegui resolver. Caso ainda possa atualizar esse repositório seria de grande ajuda, estou  conseguindo compilar mas o erro acontece justamente na utilização da biblioteca do maven. segue erro:  Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:78) ~[na:1.8.0_332]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[na:1.8.0_332]
        at java.util.Scanner.<init>(Scanner.java:563) ~[na:1.8.0_332]
        at br.com.jhemarcos.utils.FileRequestUtils.getCPFXmlRequest(FileRequestUtils.java:27) ~[cns-1.0.0.jar!/:na]
        at br.com.jhemarcos.cns.CnsDatasus.buscaPorCPF(CnsDatasus.java:24) ~[cns-1.0.0.jar!/:na]
        at br.ro.gov.portovelho.apicns.service.PatientService.findByCPF(PatientService.java:59) ~[classes!/:0.0.1-SNAPSHOT]
        at br.ro.gov.portovelho.apicns.controllers.PatientController.findByCPF(PatientController.java:24) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_332]

**Comment by jhemarcos** [comment]
Bom dia @jacksonemmerich, acabei me esquecendo disso, peço desculpas.

Realizei hoje a publicação da **versão atualizada 1.0.1** no [Sonatype OSSRH](https://central.sonatype.org/). Pode levar até 30 minutos para que a versão atualizada esteja disponível nos repositórios centrais e até 4 horas para ser listado na [pesquisa](https://search.maven.org/). (https://central.sonatype.org/publish/publish-guide/#releasing-to-central)

![image](https://user-images.githubusercontent.com/13694101/168099405-e70ecf28-9766-4885-bcd6-3642ba23d556.png)
